Adds Grades
ChicoState/SDM-Spring2023 pull request #26
Opened 2023-01-31 18:33 UTC by decoles

2023-01-31 18:37 UTC, kbuffardi requested changes

2023-01-31 18:37 UTC, kbuffardi commented on grades.md
> +- Letter grades (A through F) follow a traditional, descending 10-point scale, where the top 2 points earn a + and bottom 2 points earn a - for each letter grade. There is no extra credit nor grade i
Let's remove the bullet-point list for the opening sentence.

2023-01-31 18:37 UTC, kbuffardi commented on grades.md
> +- 40% Open Source maintenance portfolio
A list needs an empty line before it

2023-01-31 18:40 UTC, decoles commented on grades.md
> +- Letter grades (A through F) follow a traditional, descending 10-point scale, where the top 2 points earn a + and bottom 2 points earn a - for each letter grade. There is no extra credit nor grade i
Done

2023-01-31 18:41 UTC, decoles commented
Updated changes

2023-01-31 18:43 UTC, decoles reviewed
Added requested fixes

2023-02-02 19:30 UTC, kbuffardi commented
Closing since this issue has been resolved

2023-02-02 19:30 UTC, closed without merging